Init configuration vs run
powerhome/ringflux pull request #1
Opened 2017-05-31 15:33 UTC by garettarrowood

Change so configuration is always setup.

2017-05-31 15:33 UTC, garettarrowood commented
cc/ @bklang

2017-05-31 15:53 UTC, bklang requested changes

2017-05-31 15:53 UTC, bklang commented on lib/ringflux/plugin.rb
>      logger.info "Connecting to InfluxDB #{config.username}@#{config.host} with database #{config.database}"
I'd like to also include the logging clarification here

2017-05-31 17:51 UTC, garettarrowood commented on lib/ringflux/plugin.rb
>      logger.info "Connecting to InfluxDB #{config.username}@#{config.host} with database #{config.database}"
What would you like to add to the current logging?

2017-05-31 17:56 UTC, bklang commented on lib/ringflux/plugin.rb
>      logger.info "Connecting to InfluxDB #{config.username}@#{config.host} with database #{config.database}"
Change `Connecting to` to `Configuring` since no connection is made at this point

2017-06-01 14:29 UTC, bklang approved these changes

2017-06-01 14:29 UTC, merged